backend:
  name: github
  repo: matteopaul/netlify-cms-new
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pageStructure"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Contents"
        allow_add: true
        name: "contents"
        widget: "list"
        types:
          - label: "Rich Text"
            name: "rq_007"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - label: "Contents"
                name: "contents"
                widget: "list"
                types:
                  - label: "Text"
                    name: "text"
                    widget: "object"
                    fields:
                      - label: "Title"
                        name: "title"
                        widget: "string"
                      - label: "Markdown"
                        name: "md"
                        widget: "markdown"
                  - label: "Bullet List"
                    name: "bulletList"
                    widget: "object"
                    fields:
                      - label: "Title"
                        name: "title"
                        widget: "string"
                      - label: "Text"
                        name: "text"
                        widget: "string"
                      - label: "Options"
                        name: "options"
                        widget: "list"
                        allow_add: true
                        field: {label: Option, name: option, widget: string}
          - label: "Stage"
            name: "rq_013"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Button Text, name: buttonText, widget: string}
              - {label: Image, name: src, widget: image}
          - label: "Category Banner"
            name: "rq_016"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}
              - {label: Image, name: src, widget: image, required: false}
              - {label: Pfad (bitte mit einem semikolon trennen), name: path, widget: string}
          - label: "Divider"
            name: "divider"
            widget: object
            fields:
              - label: Irrelevant
                name: title
                widget: string
              - label: size
                name: size
                widget: number
          - label: "Text With Icon"
            name: "rq_011"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string, required: false}
              - {label: Icon, name: src, widget: image, required: false}
              - {label: Category Label, name: category, widget: string, required: false}
              - {label: Link Destination, name: href, widget: string, required: false}
              - {label: Link Text, name: linkText, widget: string, required: false}
          - label: "Category Banner"
            name: "rq_016"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}
              - {label: Image, name: src, widget: image, required: false}
          - label: "Category Banner"
            name: "rq_016"
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}
              - {label: Image, name: src, widget: image, required: false}

  - name: "pageContent"
    label: "Page Content"
    create: true
    identifier_field: "title"
    folder: "pageContents"
    slug: "{{type}}-{{slug}}"
    extension: "json"
    fields:
      - label: "Type:"
        name: "type"
        widget: "select"
        options:
          - {label: "Main Stage", value: "stageContentType"}
          - {label: "Promotion Banner", value: "promotionBannerContentType"}
          - {label: "Stage Banner", value: "stageBannerContentType"}
          - {label: "Quote", value: "quoteContentType"}
          - {label: "Header", value: "headerContentType"}
          - {label: "Rich Text", value: "textContentType"}
          - {label: "Bullet List", value: "bulletListContentType"}
          - {label: "Text with Icon", value: "textWithIconContentType"}
          - {label: "Image", value: "imageContentType"}
          - {label: "Card", value: "cardContentType"}
          - {label: "Content Teaser", value: "contentTeaserContentType"}
          - {label: "Attribute Filter", value: "attributeFilterContentType"}
          - {label: "Text with Card", value: "textWithCardContentType"}
          - {label: "Category Banner", value: "categoryBannerContentType"}
          - {label: "Text in Columns", value: "textInColumnsContentType"}
      - label: "Title:"
        name: "title"
        widget: "string"
      - label: "Source:"
        name: "src"
        widget: "file"
        required: false
      - label: "Button Inhalt"
        name: "buttonText"
        widget: "string"
        required: false
      - label: "Alternativtext:"
        name: "alt"
        widget: "string"
        required: false
      - label: "Textinhalt"
        name: "text"
        widget: "markdown"
        required: false
