backend:
  name: github
  repo: matteopaul/netlify-cms-new
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pageStructure"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Contents"
        allow_add: true
        name: "contents"
        widget: "list"
        fields:
          - name: "title"
            widget: "relation"
            collection: "pageContent"
            searchFields: ["title", "type", "slug"]
            valueField: "title"
            displayFields: ["title", "type"]
  - name: "pageContent"
    label: "Page Content"
    create: true
    identifier_field: "title"
    folder: "pageContents"
    slug: "{{type}}-{{slug}}"
    extension: "json"
    fields:
      - label: "Type:"
        name: "type"
        widget: "select"
        options:
          - {label: "Main Stage", value: "stageContentType"}
          - {label: "Promotion Banner", value: "promotionBannerContentType"}
          - {label: "Stage Banner", value: "stageBannerContentType"}
          - {label: "Quote", value: "quoteContentType"}
          - {label: "Header", value: "headerContentType"}
          - {label: "Rich Text", value: "textContentType"}
          - {label: "Bullet List", value: "bulletListContentType"}
          - {label: "Text with Icon", value: "textWithIconContentType"}
          - {label: "Image", value: "imageContentType"}
          - {label: "Card", value: "cardContentType"}
          - {label: "Content Teaser", value: "contentTeaserContentType"}
          - {label: "Attribute Filter", value: "attributeFilterContentType"}
          - {label: "Text with Card", value: "textWithCardContentType"}
          - {label: "Category Banner", value: "categoryBannerContentType"}
          - {label: "Text in Columns", value: "textInColumnsContentType"}
      - label: "Title:"
        name: "title"
        widget: "string"
      - label: "Source:"
        name: "src"
        widget: "file"
        required: false
      - label: "Button Inhalt"
        name: "buttonText"
        widget: "string"
        required: false
      - label: "Alternativtext:"
        name: "alt"
        widget: "string"
        required: false
      - label: "Textinhalt"
        name: "text"
        widget: "markdown"
        required: false
