backend:
  name: github
  repo: matteopaul/netlify-cms-new
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pageStructure"
    label: "PageStructure"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
